### ISSUE TITLE
Incompatible with tox 4.18.0: `TypeError: Can't instantiate abstract class CurrentEnv with abstract method python_spec_for_path`

### ISSUE THREAD

**Issue by kevalmorabia97** [fedora-python/tox-current-env#77]
```python
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/tox/run.py", line 20, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/usr/local/lib/python3.10/dist-packages/tox/run.py", line 46, in main
    return handler(state)
  File "/usr/local/lib/python3.10/dist-packages/tox/session/cmd/legacy.py", line 115, in legacy
    return run_sequential(state)
  File "/usr/local/lib/python3.10/dist-packages/tox/session/cmd/run/sequential.py", line 25, in run_sequential
    return execute(state, max_workers=1, has_spinner=False, live=True)
  File "/usr/local/lib/python3.10/dist-packages/tox/session/cmd/run/common.py", line 167, in execute
    state.envs.ensure_only_run_env_is_active()
  File "/usr/local/lib/python3.10/dist-packages/tox/session/env_select.py", line 436, in ensure_only_run_env_is_active
    envs, active = self._defined_envs, self._env_name_to_active()
  File "/usr/local/lib/python3.10/dist-packages/tox/session/env_select.py", line 258, in _defined_envs
    run_env = self._build_run_env(name)
  File "/usr/local/lib/python3.10/dist-packages/tox/session/env_select.py", line 322, in _build_run_env
    run_env = runner(args)
TypeError: Can't instantiate abstract class CurrentEnv with abstract method python_spec_for_path
```

**Comment by hroncok** [comment]
Thanks for the report.

**Comment by hroncok** [comment]
Apparently the abstract method was added in https://github.com/tox-dev/tox/pull/3325

**Comment by gaborbernat** [comment]
Sorry for the trouble here but you will need to implement this new method and release a fix ☹️

**Comment by hroncok** [comment]
Implementing the method to raise RuntimeError seems to make it work, it is never called. https://github.com/fedora-python/tox-current-env/pull/78

**Comment by gaborbernat** [comment]
It is only called if someone sets to `base_python` an absolute path 👍

**Comment by hroncok** [comment]
I wonder how to discard any custom `base_python` set. We don't care, we will always use sys.executable, that is the purpose of this plugin.

**Comment by gaborbernat** [comment]
Guess raising that RuntimeError is just fine then. or even NotImplementedError is good enough.

**Comment by hroncok** [comment]
I ended up returning the sys.executable's PythonSpec. I belive that should do it, but we really need to fix our tests.

**Comment by hroncok** [comment]
https://pypi.org/project/tox-current-env/0.0.12/
